[theme]
primaryColor = "#581845"       # roxo escuro
backgroundColor = "#F3E5F5"    # lilás bem clarinho
secondaryBackgroundColor = "#900C3F"  # vinho
textColor = "#3E1F47"          # tom de marrom-avermelhado
font = "sans serif"

#[server]
# desliga o watchdog de arquivos
#fileWatcherType = "none"

[server]
# ativa o watchdog “poll” (mais leve que o padrão “inotify”)
fileWatcherType = "poll"

[watch]
# padrões de arquivos/pastas que não serão monitorados
ignorePatterns = ["node_modules/*", ".git/*", ".venv/*", "data/*"]
